name: docto_delivery
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #state_management
  flutter_bloc: ^6.0.1
  get: ^4.1.4
  flutter_phoenix: ^0.1.0
  #UI
  solid_bottom_sheet: ^0.1.9
  #auth
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  #animations
  animation_wrappers: ^0.0.1
  #map
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  #local_storage
  get_storage: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appIcon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Icons/

