name: doctoworld_user
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  percent_indicator: ^2.1.5
  flutter_rating_bar: ^3.0.1+1
  flutter_phoenix: ^0.1.0
  flutter_bloc: ^6.0.1
  flutter_time_picker_spinner: ^1.0.6+1
  intl:

  animation_wrappers: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "DoctoWorld User"

flutter_icons:

  image_path: "assets/ixon.png"
  android: true
  ios: true


flutter:
  uses-material-design: true
  fonts:
     - family: ProductSans
       fonts:
         - asset: fonts/ProductSans-Regular.ttf
         - asset: fonts/ProductSans-Bold.ttf


  assets:
    - assets/
    - assets/CategoryImages/
    - assets/HomeBanner/
    - assets/banners/
    - assets/Categories/
    - assets/DoctorCategory/
    - assets/HomeBanner/
    - assets/Icons/
    - assets/Medicines/
    - assets/SellerImages/
    - assets/FooterIcons/
    - assets/ProfilePics/
    - assets/PaymentIcons/
    - assets/Doctors/


